version: '3.8'
services:

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - 80:80

  react-frontend:
    build:
      context: ./react-frontend
    container_name: react-frontend
    ports:
      - 3000:3000

  express-backend:
    build:
      context: ./express-backend
    container_name: express-backend
    ports:
      - 3080:3080